DRAMS/DRAMS/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from uno import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('<str:instance>/detect', views.detect, name='detect'),
    path('<str:instance>/alert', views.alert_list, name='alert'),
    path('<str:instance>/relief', views.relief_page, name='relief'),
    path('<str:instance>/feedback', views.feedback_list, name='feedback'),
    path('support', TemplateView.as_view(template_name='support.html'), name='support'),

    path('get_coordinates', views.get_coordinates, name='get_coordinates'),
    path('send_alert', views.send_alert, name='send_alert'),
    path('<str:instance>/route', views.route_solve, name='routesolve'),
    path('<str:instance>/video_feed/<int:vid>/', views.video_feed, name='video_feed'),
    path('check_video_status', views.check_video_status, name='check_video_status'),
    path('check_covid_status', views.check_covid_status, name='check_covid_status'),
    path('check_fire_status', views.check_fire_status, name='check_fire_status'),
]

DRAMS/uno/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=250, null=True)
    phone = models.CharField(max_length=29, null=True, blank=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=500, null=True, blank=True)
    gender = models.CharField(max_length=500, null=True, blank=True)
    age = models.CharField(max_length=5, null=True, blank=True)

    def __str__(self):
        return str(self.name)


class City(models.Model):
    name = models.CharField(max_length=500, null=True)
    coordinates = models.CharField(max_length=50, null=True)
    total_nodes = models.CharField(max_length=10, null=True)
    live_nodes = models.CharField(max_length=10, null=True)

    def __str__(self):
        return str(self.name)


class Location(models.Model):
    sc = (
        ("N", "None"),
        ("L", "Low"),
        ("M", "Medium"),
        ("H", "High")
    )
    ncc = (
        ("parking", "Police"),
        ("first-aid", "Ambulance"),
        ("fire-extinguisher", "Fire Brigade")
    )
    als = (
        ("N", "Not Sent"),
        ("Y", "Sent")
    )
    geography = models.CharField(max_length=500, null=True)
    coordinates = models.CharField(max_length=50, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)
    severity = models.CharField(max_length=50, null=True, choices=sc, default="N")
    population = models.BigIntegerField(null=True)
    nodal_center = models.CharField(max_length=500, null=True)
    nc_category = models.CharField(max_length=50, null=True, choices=ncc, default="first-aid")
    alert_status = models.CharField(max_length=10, null=True, choices=als, default="N")
    cctv = models.CharField(max_length=100, null=True)
    covid_status = models.CharField(max_length=5, null=True, default=0)
    fire_status = models.CharField(max_length=5, null=True, default=0)
    flood_status = models.CharField(max_length=5, null=True, default=0)

    def __str__(self):
        return str(self.geography)

DRAMS/uno/views/alert.py
from django.core.mail import EmailMessage
from django.views.decorators.csrf import csrf_exempt
from uno.models import *
from twilio.rest import Client

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse


twilio_account_sid = 'AC5ea8bb59991689451ceaf29ade8f320e'
twilio_auth_token = '7094c5b698252c3f9ab86103d2b22f23'
client = Client(twilio_account_sid, twilio_auth_token)


def alert_list(request, instance):
    if instance == "covid":
        alertlist = Location.objects.filter(covid_status=1)
    elif instance == "flood":
        alertlist = Location.objects.filter(flood_status=1)
    elif instance == "fire":
        alertlist = Location.objects.filter(fire_status=1)
    if len(alertlist) == 0:
        alertlist = None
    return render(request, instance+'/alert.html', {'al': alertlist, 'instance': instance})


@csrf_exempt
def send_alert(request):
    med = request.POST.get("med")
    sub = request.POST.get("subject")
    body = request.POST.get("body")
    res = {"msg": None, "email": None}

    users = User.objects.all()
    for user in users:
        if "e" in med and user.email is not None:
            email = EmailMessage(
                sub, body, from_email="hariharanr.sc73@gmail.com", to=[user.email]
            )
            email.send()

        if "s" in med and user.phone is not None:
            message = client.messages.create(
                body=body,
                from_='+12057518316',
                to='+91'+str(user.phone)
            )
            if message.error_code is None:
                res["msg"] = True
            else:
                res["msg"] = False

    return JsonResponse(res)

DRAMS/uno/views/detect.py
from django.http import StreamingHttpResponse, HttpResponseServerError
from django.views.decorators import gzip
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.decorators.csrf import csrf_exempt
from uno.models import City, Location
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

from uno.defaults import COVID, FIRE
import random

from .predictdisaster import PredictDisaster
from collections import deque
import threading
import time
import os
import cv2
import numpy as np


fps = 24
outputFrame = {}
t = {}

# initialize the predictions queue
size = 120
Q = deque(maxlen=size)

nov = [0, 0]
count_covid = [0, 0]

sev = 0
count_fire = 0


def predict_frame(vid):
    # grab global references to the video stream, output frame, and lock variables
    global outputFrame

    frame = outputFrame['vid'+str(vid)]

    pd = PredictDisaster()
    # loop over frames from the video file stream
    while True:

        if frame is None:
            continue

        frame_preds = pd.predict(frame)

        if frame_preds is not None:
            Q.append(frame_preds)
            # perform prediction averaging over the current
            results = np.array(Q).mean(axis=0)
            i = np.argmax(results)
            label = i
            print(str(vid) + ": " + str(label))
            node = Location.objects.get(cctv=str(vid))
            node.disaster_status = str(1-label)
            node.save()


def generate(vs, vid, instance):
    # grab global references to the output frame and lock variables
    global outputFrame, nov, count_covid, COVID, sev, count_fire, FIRE

    # loop over frames from the video file stream
    while True:
        # read the next frame from the file
        grabbed, frame = vs.read()
        time.sleep(1 / (fps-random.randint(0, 14)))

        # if the frame was not grabbed, then we have reached the end
        # of the stream
        if not grabbed:
            outputFrame['vid'+str(vid)] = None
            break

        outputFrame['vid'+str(vid)] = frame.copy()

        if "covid" in instance:
            cov = COVID[str(vid)]
            ind = count_covid[vid-1]
            nov[vid-1] = cov[ind]
            count_covid[vid-1] = count_covid[vid-1] + 1
        elif "fire" in instance:
            if vid == 2:
                sev = FIRE[count_fire]
                count_fire = count_fire + 1

        # encode the frame in JPEG format
        flag, encodedImage = cv2.imencode(".jpg", frame)

        # ensure the frame was successfully encoded
        if not flag:
            continue

        # yield the output frame in the byte format
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + encodedImage.tobytes() + b'\r\n\r\n')


@gzip.gzip_page
def video_feed(request, vid, instance):
    try:
        # initialize the video stream
        videofile = os.path.sep.join([os.getcwd(), staticfiles_storage.url('vids/'+instance+str(vid)+'.mp4')])
        vs = cv2.VideoCapture(videofile)

        grabbed, frame = vs.read()
        if grabbed:
            outputFrame['vid' + str(vid)] = frame.copy()

        # try:
        #     if vid == 3:
        #         t['vid' + str(vid)] = threading.Thread(target=predict_frame, args=(vid,))
        #         t['vid' + str(vid)].daemon = True
        #         t['vid' + str(vid)].start()
        # except KeyError as e:
        #     print(e)

        return StreamingHttpResponse(generate(vs, vid, instance), content_type="multipart/x-mixed-replace;boundary=frame")
    except:
        print("***********")
        return None


def detect(request, instance):
    global count_fire, count_covid
    count_fire = 0
    count_covid = [0, 0]
    cities = City.objects.all()
    if len(cities) > 0:
        cn = []
        for city in cities:
            cn.append({"id": city.id, "name": city.name})
    else:
        cn = None

    return render(request, instance+'/detect.html', {'cities': cn, 'instance': instance})


@csrf_exempt
def get_coordinates(request):
    cid = request.POST.get("cid")
    city = City.objects.get(id=int(cid))
    coord = city.coordinates.split(",")

    locs = Location.objects.filter(city=city)
    nodes = []
    for loc in locs:
        nodes.append({
            'name': loc.geography,
            'coordinates': loc.coordinates.split(','),
            'cctvurl': loc.cctv
        })
    data = {
        "lat": float(coord[0]),
        "lng": float(coord[1]),
        "tot": city.total_nodes,
        "live": city.live_nodes,
        "nodes": nodes
    }
    return JsonResponse(data)


@csrf_exempt
def check_video_status(request):
    cid = request.POST.get("cid")
    city = City.objects.get(id=int(cid))
    locs = Location.objects.filter(city=city)
    nodes = []
    for loc in locs:
        nodes.append({
            'cctvurl': loc.cctv,
            'status': loc.flood_status
        })
    data = {
        "nodes": nodes
    }
    return JsonResponse(data)


@csrf_exempt
def check_covid_status(request):
    global nov
    data = {}
    c = 1
    for n in nov:
        data[str(c)] = str(n)
        c = c + 1

    return JsonResponse(data)


@csrf_exempt
def check_fire_status(request):
    global sev
    data = {
        "sev": str(sev)
    }
    return JsonResponse(data)

DRAMS/templates/covid/alert.html
{% extends 'covid/base.html' %}
{% load static %}

{% block title %}DRAMS{% endblock title %}

{% block css %}
    <style>
        .msgbtn {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }
        #mbb {
            display: none;
        }
        tbody tr:hover {
            background-color: #eee;
            cursor: pointer;
        }
        label {
            font-weight: bold;
        }

        .selected {
            background-color: lightgreen !important;
            font-weight: bold;
        }
    </style>
{% endblock css %}

{% block pagetitle %}Warn{% endblock %}

{% block content %}
    {% if al is None %}
        <div class="card shadow mb-4">
            <div class="card-body">
                No data available.
            </div>
        </div>
    {% else %}
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>Geography</th>
                                <th>Severity</th>
                                <th>Population</th>
                                <th>Nearest Nodal Center</th>
                                <th>Alert Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for p in al %}
                                <tr class="locr">
                                    <td>{{ p.geography }}</td>
                                    <td>{{ p.get_severity_display }}</td>
                                    <td>{{ p.population }}</td>
                                    <td>{{ p.nodal_center }} &nbsp <i class="ncc fas fa-{{ p.nc_category }}" data-container="body" data-toggle="popover" data-placement="top" data-content="{{ p.get_nc_category_display }}"></i></td>
                                    <td>Not Sent</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
         <a id="mbb" class="btn btn-primary msgbtn" style="border-radius: 50px; font-size: 1.35rem; width: 180px; height: 3.5rem; color: #fff; text-align: left; background-color: #2e59d9 !important;">
             <span style="position:relative; top: 5px">Send Warning</span>
         </a>
        <a id="mbs" class="btn btn-primary btn-circle btn-lg msgbtn shadow" style="color: #fff;" data-toggle="modal" data-target="#message">
            <i class="fas fa-exclamation-triangle"></i>
        </a>
    {% endif %}
{% endblock content %}

{% block modals %}
    <div class="modal fade" id="message" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Alert Message</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="messageform" action="{% url 'send_alert' %}">
                    <div class="modal-body">
                        <div class="form-group row">
                            <label for="subject" class="col-sm-2 col-form-label">Subject</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="subject" value="SAFETY ALERT! Crowd detected near your location">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="msgbody">Message</label>
                            <textarea class="form-control" id="msgbody" value="Message" rows="10" style="resize: none;">
Your location has been deemed crowded. Kindly take proper precautions and ensure social distancing for your safety and those around you.
For any assistance please call - 9876543210
                            </textarea>
                        </div>
                        <div class="form-group row">
                            <label for="subject" class="col-sm-2 col-form-label">Medium</label>
                            <div class="col-sm-10">
                                <div class="form-group" style="position: relative; top: 7px;">
                                    <div class="form-check form-check-inline">
                                      <input class="form-check-input" type="checkbox" id="emailc" value="email">
                                      <label class="form-check-label" for="emailc" style="font-weight: normal">
                                          <i class="fas fa-envelope ml-2"></i>
                                          Email
                                      </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                      <input class="form-check-input" type="checkbox" id="smsc" value="sms">
                                      <label class="form-check-label" for="smsc" style="font-weight: normal">
                                          <i class="fas fa-sms ml-2"></i>
                                          SMS
                                      </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
          $('#dataTable').DataTable();
        });
        $(function () {
            $('.ncc').popover({
              container: 'body',
              trigger: 'hover'
            })
        });
        $("#mbs").hover(function() {
            $("#mbb").css("display", "block");
        }, function() {
            $("#mbb").css("display", "none");
        });

        $(".locr").click(function () {
            $(this).toggleClass("selected");
        });
    </script>
    <script>

        $("#messageform").submit(function(event) {
          event.preventDefault();
          var form = $(this), url = form.attr('action');

          var med = "";
          var cc = true;
          if ($("#emailc").prop("checked") === true) {
            med += "e";
            cc = false;
        }
          if ($("#smsc").prop("checked") === true) {
            med += "s";
            cc = false;
        }
          if (cc) {
              alert("Select at least one medium of message");
              return false;
          }
          var data = {"subject": $("#subject").val(), "body": $("#msgbody").val(), "med": med};
          $.ajax({
                type: "POST",
                url: url,
                data: data,
                contentType: "application/x-www-form-urlencoded",
                success: function(responseData, textStatus, jqXHR) {
                    console.log("success");
                    $('#message').modal('toggle');
                    var sel = document.getElementsByClassName("selected");
                    var cols, col;
                    for (var i = 0; i < sel.length; i++) {
                        cols = sel[i].getElementsByTagName("td");
                        col = cols[cols.length - 1];
                        col.innerHTML = "Sent";
                    }
                    $(".selected").toggleClass("selected");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });
        });
    </script>
{% endblock script %}

DRAMS/templates/covid/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>{% block title %}DRAMS{% endblock title %}</title>
        <!-- Custom fonts for this template-->
        <script src="https://kit.fontawesome.com/1cc5ac35f0.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
        {% block css %}
        {% endblock css %}
    </head>
    <body id="page-top">
        <!-- Page Wrapper -->
        <div id="wrapper">
            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
                    <div class="sidebar-brand-icon">
                        <img src="{% static 'img/logo.png' %}" style="max-height: 30px;">
                    </div>
                    <div class="sidebar-brand-text mx-3">DRAMS</div>
                </a>
                <hr class="sidebar-divider mb-0">
                <hr class="sidebar-divider">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'detect' instance %}">
                        <i class="fas fa-map-marked-alt"></i>
                        <span>Detect</span>
                    </a>
                </li>
                <hr class="sidebar-divider mb-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alert' instance %}">
                        <i class="fas fa-exclamation-circle"></i>
                        <span>Warn </span>
                    </a>
                </li>
                <hr class="sidebar-divider mb-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'relief' instance %}">
                        <i class="fas fa-street-view"></i>
                        <span>Disperse</span>
                    </a>
                </li>
                <hr class="sidebar-divider mb-0">
                <hr class="sidebar-divider mb-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feedback' instance %}">
                        <i class="fas fa-comment-dots"></i>
                        <span>Feedback</span>
                    </a>
                </li>
                <hr class="sidebar-divider mb-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'support' %}">
                        <i class="fas fa-question-circle"></i>
                        <span>Support</span>
                    </a>
                </li>
                <hr class="sidebar-divider mb-0">
            </ul>
            <div id="content-wrapper" class="d-flex flex-column">
                <div id="content">
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                        <h1 class="h4 mt-2 ml-2 text-gray-800 text-uppercase font-weight-bold">{% block pagetitle %}Blank page{% endblock %}</h1>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                            	<a href="{% url 'index' %}" class="btn btn-primary">Run Another Instance</a>
                            </li>
                        </ul>
                    </nav>
                    <div class="container-fluid">
                        {% block content %}
                            If you see this, something is wrong!
                        {% endblock content %}
                    </div>
                </div>
                <!-- <footer class="sticky-footer bg-white mt-5">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto"><span>Copyright &copy; Your Website 2020</span></div>
                    </div>
                </footer> -->
            </div>
        </div>

        {% block modals %}
        {% endblock modals %}
        
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
        {% block script %}
        {% endblock script %}
    </body>
</html>

DRAMS/templates/covid/feedback.html
{% extends 'covid/base.html' %}
{% load static %}

{% block title %}DRAMS{% endblock title %}

{% block css %}
    <style>
        .feedback {
            color: white !important;
        }
    </style>
{% endblock css %}

{% block pagetitle %}Feedback{% endblock %}

{% block content %}
    {% if al is None %}
        <div class="card shadow mb-4">
            <div class="card-body">
                No data to display.
            </div>
        </div>
    {% else %}
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>Geography</th>
                                <th>Severity</th>
                                <th>Population</th>
                                <th style="text-align: center">Feedback</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for p in al %}
                                {% with forloop.counter|stringformat:"i" as id %}
                                    {% with "rid"|add:id as rid %}
                                        <tr id="{{ rid }}" class="rids">
                                            <td>{{ p.geography }}</td>
                                            <td>{{ p.get_severity_display }}</td>
                                            <td>{{ p.population }}</td>
                                            <td style="text-align: center">
                                                <a class="btn btn-primary feedback" onclick='removerow("{{ rid }}")'>Correct</a>
                                                <a class="btn btn-danger feedback" onclick='removerow("{{ rid }}")'>Incorrect</a>
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

{% block modals %}
{% endblock %}

{% block script %}
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
          $('#dataTable').DataTable();
        });
        function removerow(rid) {
            $("#"+rid).remove();
            if ($('.rids').length === 0) {
                $('.card-body').html("No data to display.")
            }
        }
    </script>
{% endblock script %}s